# Generated by Django 4.0 on 2021-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('url', models.URLField()),
                ('website_name', models.TextField()),
                ('collected_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
